using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_BreadData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_BreadData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_BreadData(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4952991553639720483UL,6612269086872772224UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String breadCode
	{
		get => _breadCode[Index];
		set => _breadCode[Index] = value;
	}
	public System.String breadName
	{
		get => _breadName[Index];
		set => _breadName[Index] = value;
	}
	public System.String breadInfo
	{
		get => _breadInfo[Index];
		set => _breadInfo[Index] = value;
	}
	public System.String breadPrice
	{
		get => _breadPrice[Index];
		set => _breadPrice[Index] = value;
	}
	public System.String breadRank
	{
		get => _breadRank[Index];
		set => _breadRank[Index] = value;
	}
	public System.Collections.Generic.List<System.Boolean> breadingredients
	{
		get => _breadingredients[Index];
		set => _breadingredients[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5491952312576196023UL, 12982183607831491246UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_breadCode;
	public static BansheeGz.BGDatabase.BGFieldString _breadCode => _ufle12jhs77_breadCode ?? (_ufle12jhs77_breadCode = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5285091491913776619UL, 6873074582721137036UL), () => _ufle12jhs77_breadCode = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_breadName;
	public static BansheeGz.BGDatabase.BGFieldString _breadName => _ufle12jhs77_breadName ?? (_ufle12jhs77_breadName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5375429271485647238UL, 9034236725269061801UL), () => _ufle12jhs77_breadName = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_breadInfo;
	public static BansheeGz.BGDatabase.BGFieldString _breadInfo => _ufle12jhs77_breadInfo ?? (_ufle12jhs77_breadInfo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5004549205584049158UL, 4835109382693009304UL), () => _ufle12jhs77_breadInfo = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_breadPrice;
	public static BansheeGz.BGDatabase.BGFieldString _breadPrice => _ufle12jhs77_breadPrice ?? (_ufle12jhs77_breadPrice = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5328798846823438355UL, 72485095917751956UL), () => _ufle12jhs77_breadPrice = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_breadRank;
	public static BansheeGz.BGDatabase.BGFieldString _breadRank => _ufle12jhs77_breadRank ?? (_ufle12jhs77_breadRank = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5017511022432139710UL, 8965654910642919087UL), () => _ufle12jhs77_breadRank = null));
	private static BansheeGz.BGDatabase.BGFieldListBool _ufle12jhs77_breadingredients;
	public static BansheeGz.BGDatabase.BGFieldListBool _breadingredients => _ufle12jhs77_breadingredients ?? (_ufle12jhs77_breadingredients = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldListBool>(MetaDefault, new BGId(5460206322981000020UL, 6781316340541157305UL), () => _ufle12jhs77_breadingredients = null));
	private static readonly DB_BreadData.Factory _factory0_PFS = new DB_BreadData.Factory();
	private DB_BreadData() : base(MetaDefault) {}
	private DB_BreadData(BGId id) : base(MetaDefault, id) {}
	private DB_BreadData(BGMetaEntity meta) : base(meta) {}
	private DB_BreadData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_BreadData FindEntity(Predicate<DB_BreadData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_BreadData> FindEntities(Predicate<DB_BreadData> filter, List<DB_BreadData> result=null, Comparison<DB_BreadData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_BreadData> action, Predicate<DB_BreadData> filter=null, Comparison<DB_BreadData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_BreadData GetEntity(BGId entityId) => (DB_BreadData) MetaDefault.GetEntity(entityId);
	public static DB_BreadData GetEntity(int index) => (DB_BreadData) MetaDefault[index];
	public static DB_BreadData GetEntity(string entityName) => (DB_BreadData) MetaDefault.GetEntity(entityName);
	public static DB_BreadData NewEntity() => (DB_BreadData) MetaDefault.NewEntity();
	public static DB_BreadData NewEntity(BGId entityId) => (DB_BreadData) MetaDefault.NewEntity(entityId);
	public static DB_BreadData NewEntity(Action<DB_BreadData> callback) => (DB_BreadData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_BreadData)entity)));
}
#pragma warning restore 414
